# Copyright (c) 2026, Renaud Allard <renaud@allard.it>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""Postcode → utility resolver.

Two layers of resolution:

  1. Wallonia (postcodes 4000-7999) uses ``_PER_POSTCODE``,
     a 496-entry dict generated by ``scripts/refresh_postcodes.py``
     from the Géoportail Wallonie ZDE GeoPackage (CC BY 4.0,
     dataset id ``d08e993e-bb1d-4322-a044-2aa7bfc03247``). For each
     Walloon postcode polygon the script point-in-polygon-queries
     the ArcGIS REST endpoint to learn which DISTRIBUTEUR serves it,
     then maps the official name to our utility id. Postcodes whose
     distributor is one of the ~30 régies communales we don't ship
     an extractor for are intentionally absent and fall through to
     the manual utility picker. Re-run the refresh script annually.

  2. Brussels + Flanders use range-based rules with hand-curated /
     scrape-derived carve-outs (AGSO Knokke-Heist, the 6 Aquaduin
     Westkust postcodes, and a DWG carve-out for the 121 unambiguous
     DWG-served postcodes scattered inside the 8000-9999 Farys
     block). The DWG carve-out is generated by
     ``scripts/refresh_postcodes.py`` from DWG's and Farys's
     (post-filter) commune dropdowns and includes only postcodes
     that DWG serves and Farys doesn't.

  3. 8 postcodes are genuinely split between two or three operators
     at street level (1770 Liedekerke, 8020 Oostkamp, 8400 Oostende,
     8450 Bredene, 8490 Jabbeke, 9080 Lochristi, 9550 Herzele, 9570
     Lierde). For these, ``resolve_candidates`` returns the full
     candidate tuple and the config flow asks the user to pick. The
     ``resolve`` helper still returns a single "dominant" operator
     (the first candidate) for backwards compatibility.

Coverage:

  * 1000-1299    Brussels-Capital                       → VIVAQUA
  * 1300-1499    Brabant Wallon                         → inBW
  * 1500-1999,
    3000-3999    Vlaams-Brabant + Halle-Vilvoorde
                 + Limburg                              → DE WATERGROEP
  * 2000-2070    Antwerp city core                      → WATER-LINK
  * 2100-2999    Rest of Antwerp province               → PIDPA
                 (Water-link's ring communes -- Edegem,
                  Hove, Mortsel, Schoten, Beveren, etc.
                  -- need the manual picker; their
                  postcodes overlap with Pidpa's wider
                  service area so we default to Pidpa
                  outside the city core)
  * 4000-7999    Per the ZDE-derived
                 ``_PER_POSTCODE`` table       → SWDE / CILE /
                                                           inBW / INASEP /
                                                           AIEC / AIEM /
                                                           CIESAC / IDEN /
                                                           IEG (régies
                                                           absent → manual)
  * 8300, 8301   Knokke-Heist                           → AGSO Knokke-Heist
  * 8430, 8450,
    8620, 8630,
    8660, 8670   Aquaduin Westkust communes             → AQUADUIN
  * 8000-9999 (DWG-served carve-out, 121 postcodes)     → DE WATERGROEP
  * 1770, 8020, 8400,
    8450, 8490, 9080,
    9550, 9570       Real splits (two or three ops)     → multi-choice
  * 8000-9999 (rest, mostly Oost-Vl. and West-Vl.)      → FARYS
  * everything else                                     → unresolved
"""

from __future__ import annotations

# Aquaduin's 6 Westkust communes (Koksijde, De Panne, Nieuwpoort, Veurne,
# Bredene, Middelkerke). Hand-curated because they're scattered inside the
# 8000-8999 West-Vlaanderen block where Farys would otherwise be the default.
_AQUADUIN_POSTCODES: frozenset[int] = frozenset(
    {
        8430,  # Middelkerke
        8450,  # Bredene
        8620,  # Nieuwpoort
        8630,  # Veurne
        8660,  # De Panne
        8670,  # Koksijde
    }
)


# DWG-served postcodes inside the otherwise-Farys 8000-9999 block.
# Generated by scripts/refresh_postcodes.py from DWG's and Farys's
# (post-filter) commune dropdowns: every postcode DWG lists that
# Farys does not. Currently 121 postcodes (Kortrijk, Harelbeke,
# Roeselare, Waregem, Ieper, Sint-Niklaas's outer parishes, Eeklo,
# Maldegem, etc.). Re-run the refresh script if DWG's coverage
# changes.
#
# Postcodes genuinely split between two or three operators at street
# level live in ``_SPLIT_POSTCODES`` below; the config flow asks the
# user to pick one of the candidates rather than guessing.
_DWG_POSTCODES_FLANDERS: frozenset[int] = frozenset(
    {
        8210,  # Veldegem (Zedelgem)
        8211,  # Aartrijke (Zedelgem)
        8432,  # Leffinge (Middelkerke)
        8460,  # Westkerke (Oudenburg)
        8470,  # Moere (Gistel)
        8480,  # Ichtegem (Ichtegem)
        8500,  # Kortrijk (Kortrijk)
        8501,  # Bissegem (Kortrijk)
        8510,  # Bellegem (Kortrijk)
        8511,  # Aalbeke (Kortrijk)
        8520,  # Kuurne (Kuurne)
        8530,  # Harelbeke (Harelbeke)
        8531,  # Hulste (Harelbeke)
        8540,  # Deerlijk (Deerlijk)
        8550,  # Zwevegem (Zwevegem)
        8551,  # Heestert (Zwevegem)
        8552,  # Moen (Zwevegem)
        8553,  # Otegem (Zwevegem)
        8554,  # Sint-Denijs (Zwevegem)
        8560,  # Moorsele (Wevelgem)
        8570,  # Ingooigem (Anzegem)
        8572,  # Kaster (Anzegem)
        8573,  # Tiegem (Anzegem)
        8580,  # Avelgem (Avelgem)
        8581,  # Kerkhove (Avelgem)
        8582,  # Outrijve (Avelgem)
        8583,  # Bossuit (Avelgem)
        8587,  # Spiere (Spiere-Helkijn)
        8600,  # Diksmuide (Diksmuide)
        8610,  # Handzame (Kortemark)
        8640,  # Oostvleteren (Vleteren)
        8647,  # Noordschote (Lo-Reninge)
        8650,  # Houthulst (Houthulst)
        8680,  # Bovekerke (Koekelare)
        8700,  # Aarsele (Tielt)
        8710,  # Sint-Baafs-Vijve (Wielsbeke)
        8720,  # Dentergem (Dentergem)
        8740,  # Pittem (Pittem)
        8750,  # Wingene (Wingene)
        8760,  # Meulebeke (Tielt)
        8770,  # Ingelmunster (Ingelmunster)
        8780,  # Oostrozebeke (Oostrozebeke)
        8790,  # Waregem (Waregem)
        8791,  # Beveren-Leie (Waregem)
        8792,  # Desselgem (Waregem)
        8793,  # Sint-Eloois-Vijve (Waregem)
        8800,  # Roeselare (Roeselare)
        8810,  # Lichtervelde (Lichtervelde)
        8820,  # Torhout (Torhout)
        8830,  # Gits (Hooglede)
        8840,  # Staden (Staden)
        8850,  # Ardooie (Ardooie)
        8851,  # Koolskamp (Ardooie)
        8860,  # Lendelede (Lendelede)
        8870,  # Emelgem (Izegem)
        8880,  # Ledegem (Ledegem)
        8890,  # Moorslede (Moorslede)
        8900,  # Dikkebus (Ieper)
        8902,  # Voormezele (Ieper)
        8904,  # Boezinge (Ieper)
        8906,  # Elverdinge (Ieper)
        8908,  # Vlamertinge (Ieper)
        8920,  # Bikschote (Langemark-Poelkapelle)
        8930,  # Lauwe (Menen)
        8940,  # Geluwe (Wervik)
        8950,  # Nieuwkerke (Heuvelland)
        8951,  # Dranouter (Heuvelland)
        8952,  # Wulvergem (Heuvelland)
        8953,  # Wijtschate (Heuvelland)
        8954,  # De Klijte (Heuvelland)
        8956,  # Kemmel (Heuvelland)
        8957,  # Mesen (Mesen)
        8958,  # Loker (Heuvelland)
        8970,  # Reningelst (Poperinge)
        8972,  # Roesbrugge-Haringe (Poperinge)
        8978,  # Watou (Poperinge)
        8980,  # Beselare (Zonnebeke)
        9100,  # Nieuwkerken-Waas (Sint-Niklaas)
        9111,  # Belsele (Sint-Niklaas)
        9112,  # Sinaai (Sint-Niklaas)
        9120,  # Beveren (Beveren-Kruibeke-Zwijndrecht)
        9130,  # Doel (Beveren-Kruibeke-Zwijndrecht)
        9140,  # Steendorp (Temse)
        9150,  # Kruibeke (Beveren-Kruibeke-Zwijndrecht)
        9160,  # Lokeren (Lokeren)
        9170,  # De Klinge (Sint-Gillis-Waas)
        9180,  # Moerbeke-Waas (Lokeren)
        9185,  # Wachtebeke (Lochristi)
        9190,  # Kemzeke (Stekene)
        9240,  # Zele (Zele)
        9250,  # Waasmunster (Waasmunster)
        9270,  # Laarne (Laarne)
        9290,  # Uitbergen (Berlare)
        9400,  # Appelterre (Ninove)
        9401,  # Pollare (Ninove)
        9402,  # Meerbeke (Ninove)
        9403,  # Neigem (Ninove)
        9404,  # Aspelare (Ninove)
        9406,  # Outer (Ninove)
        9450,  # Denderhoutem (Haaltert)
        9470,  # Denderleeuw (Denderleeuw)
        9472,  # Iddergem (Denderleeuw)
        9473,  # Welle (Denderleeuw)
        9500,  # Nederboelare (Geraardsbergen)
        9506,  # Idegem (Geraardsbergen)
        9571,  # Hemelveerdegem (Lierde)
        9900,  # Eeklo (Eeklo)
        9940,  # Ertvelde (Evergem)
        9950,  # Lievegem (Lievegem)
        9960,  # Assenede (Assenede)
        9961,  # Boekhoute (Assenede)
        9968,  # Oosteeklo (Assenede)
        9970,  # Kaprijke (Kaprijke)
        9971,  # Lembeke (Kaprijke)
        9980,  # Sint-Laureins (Sint-Laureins)
        9981,  # Sint-Margriete (Sint-Laureins)
        9982,  # Sint-Jan-in-Eremo (Sint-Laureins)
        9988,  # Watervliet (Sint-Laureins)
        9990,  # Maldegem (Maldegem)
        9991,  # Adegem (Maldegem)
        9992,  # Middelburg (Maldegem)
    }
)


# Generated by scripts/refresh_postcodes.py from the Géoportail Wallonie
# ZDE GeoPackage (Zones de Distribution en Eau, CC BY 4.0, dataset id
# d08e993e-bb1d-4322-a044-2aa7bfc03247). 496 postcodes resolved as of
# 2026; postcodes served by régies communales we don't ship extractors
# for are intentionally absent and fall through to the manual picker.
_PER_POSTCODE: dict[str, str] = {
    "4000": "cile",
    "4020": "cile",
    "4030": "cile",
    "4031": "cile",
    "4032": "cile",
    "4040": "cile",
    "4041": "cile",
    "4042": "cile",
    "4050": "cile",
    "4051": "cile",
    "4052": "cile",
    "4053": "cile",
    "4099": "cile",
    "4100": "cile",
    "4101": "cile",
    "4102": "cile",
    "4120": "swde",
    "4121": "swde",
    "4122": "swde",
    "4130": "cile",
    "4140": "swde",
    "4141": "swde",
    "4160": "cile",
    "4161": "cile",
    "4162": "cile",
    "4163": "cile",
    "4170": "cile",
    "4171": "cile",
    "4180": "cile",
    "4181": "cile",
    "4190": "swde",
    "4210": "swde",
    "4217": "swde",
    "4218": "swde",
    "4219": "swde",
    "4250": "swde",
    "4252": "swde",
    "4253": "swde",
    "4254": "swde",
    "4257": "swde",
    "4260": "swde",
    "4261": "swde",
    "4263": "swde",
    "4280": "swde",
    "4287": "swde",
    "4300": "swde",
    "4317": "swde",
    "4340": "cile",
    "4342": "cile",
    "4347": "cile",
    "4350": "swde",
    "4351": "swde",
    "4357": "swde",
    "4360": "swde",
    "4367": "swde",
    "4400": "cile",
    "4420": "cile",
    "4430": "cile",
    "4431": "cile",
    "4432": "cile",
    "4450": "swde",
    "4451": "swde",
    "4452": "swde",
    "4453": "swde",
    "4458": "swde",
    "4460": "cile",
    "4470": "swde",
    "4480": "swde",
    "4500": "cile",
    "4520": "swde",
    "4530": "swde",
    "4537": "swde",
    "4540": "swde",
    "4550": "iden",
    "4557": "cile",
    "4560": "ciesac",
    "4570": "cile",
    "4577": "cile",
    "4590": "cile",
    "4600": "cile",
    "4601": "cile",
    "4602": "cile",
    "4606": "swde",
    "4607": "swde",
    "4608": "swde",
    "4610": "cile",
    "4620": "cile",
    "4621": "cile",
    "4623": "cile",
    "4624": "cile",
    "4630": "swde",
    "4631": "swde",
    "4632": "swde",
    "4633": "swde",
    "4650": "swde",
    "4651": "swde",
    "4652": "swde",
    "4653": "swde",
    "4654": "swde",
    "4670": "cile",
    "4671": "cile",
    "4672": "cile",
    "4680": "swde",
    "4681": "swde",
    "4682": "swde",
    "4683": "swde",
    "4684": "swde",
    "4690": "swde",
    "4700": "swde",
    "4701": "swde",
    "4710": "swde",
    "4711": "swde",
    "4730": "swde",
    "4731": "swde",
    "4783": "swde",
    "4800": "swde",
    "4801": "swde",
    "4802": "swde",
    "4820": "swde",
    "4821": "swde",
    "4837": "swde",
    "4840": "swde",
    "4841": "swde",
    "4845": "swde",
    "4850": "swde",
    "4851": "swde",
    "4852": "swde",
    "4860": "swde",
    "4861": "swde",
    "4870": "swde",
    "4877": "swde",
    "4880": "swde",
    "4890": "swde",
    "4900": "swde",
    "4920": "swde",
    "4950": "swde",
    "4960": "swde",
    "4970": "swde",
    "4990": "swde",
    "5000": "swde",
    "5001": "swde",
    "5002": "swde",
    "5003": "swde",
    "5004": "swde",
    "5010": "swde",
    "5012": "swde",
    "5020": "swde",
    "5021": "swde",
    "5022": "swde",
    "5024": "swde",
    "5030": "swde",
    "5031": "swde",
    "5032": "swde",
    "5060": "swde",
    "5070": "inasep",
    "5080": "swde",
    "5081": "swde",
    "5100": "swde",
    "5101": "swde",
    "5140": "swde",
    "5150": "swde",
    "5170": "swde",
    "5190": "swde",
    "5300": "swde",
    "5310": "swde",
    "5330": "swde",
    "5332": "swde",
    "5333": "swde",
    "5334": "swde",
    "5336": "swde",
    "5340": "swde",
    "5350": "swde",
    "5351": "swde",
    "5352": "swde",
    "5353": "swde",
    "5354": "swde",
    "5360": "aiec",
    "5361": "aiec",
    "5362": "aiec",
    "5363": "aiec",
    "5364": "swde",
    "5370": "aiec",
    "5372": "aiec",
    "5374": "aiec",
    "5376": "aiec",
    "5377": "aiec",
    "5380": "swde",
    "5500": "swde",
    "5501": "swde",
    "5502": "swde",
    "5503": "swde",
    "5504": "swde",
    "5520": "aiem",
    "5521": "aiem",
    "5522": "aiem",
    "5523": "aiem",
    "5524": "aiem",
    "5530": "swde",
    "5537": "aiem",
    "5540": "swde",
    "5541": "swde",
    "5542": "inasep",
    "5543": "inasep",
    "5544": "inasep",
    "5560": "swde",
    "5561": "swde",
    "5562": "swde",
    "5563": "inasep",
    "5564": "inasep",
    "5570": "swde",
    "5571": "swde",
    "5572": "inasep",
    "5573": "inasep",
    "5574": "inasep",
    "5576": "inasep",
    "5590": "aiec",
    "5600": "inasep",
    "5620": "inasep",
    "5621": "inasep",
    "5630": "inasep",
    "5640": "aiem",
    "5641": "aiem",
    "5644": "aiem",
    "5646": "aiem",
    "5650": "inasep",
    "5651": "inasep",
    "5660": "inasep",
    "5670": "inasep",
    "5680": "swde",
    "6000": "swde",
    "6001": "swde",
    "6010": "swde",
    "6020": "swde",
    "6030": "swde",
    "6031": "swde",
    "6032": "swde",
    "6040": "swde",
    "6041": "swde",
    "6042": "swde",
    "6043": "swde",
    "6044": "swde",
    "6060": "swde",
    "6061": "swde",
    "6075": "swde",
    "6099": "swde",
    "6110": "swde",
    "6111": "swde",
    "6120": "swde",
    "6140": "swde",
    "6141": "swde",
    "6142": "swde",
    "6150": "swde",
    "6180": "swde",
    "6181": "swde",
    "6182": "swde",
    "6183": "swde",
    "6200": "swde",
    "6210": "swde",
    "6211": "swde",
    "6220": "swde",
    "6221": "swde",
    "6222": "swde",
    "6223": "swde",
    "6224": "swde",
    "6230": "swde",
    "6238": "swde",
    "6240": "swde",
    "6250": "swde",
    "6280": "swde",
    "6440": "swde",
    "6441": "swde",
    "6461": "swde",
    "6462": "swde",
    "6463": "swde",
    "6470": "swde",
    "6500": "swde",
    "6511": "swde",
    "6530": "swde",
    "6531": "swde",
    "6532": "swde",
    "6533": "swde",
    "6534": "swde",
    "6536": "swde",
    "6540": "swde",
    "6542": "swde",
    "6543": "swde",
    "6560": "swde",
    "6567": "swde",
    "6590": "swde",
    "6591": "swde",
    "6592": "swde",
    "6593": "swde",
    "6594": "swde",
    "6596": "swde",
    "6600": "swde",
    "6630": "swde",
    "6637": "swde",
    "6640": "swde",
    "6660": "swde",
    "6661": "swde",
    "6662": "swde",
    "6663": "swde",
    "6666": "swde",
    "6680": "swde",
    "6681": "swde",
    "6686": "swde",
    "6687": "swde",
    "6688": "swde",
    "6690": "swde",
    "6692": "swde",
    "6698": "swde",
    "6700": "swde",
    "6704": "swde",
    "6706": "swde",
    "6780": "swde",
    "6781": "swde",
    "6782": "swde",
    "6790": "swde",
    "6791": "swde",
    "6792": "swde",
    "6820": "swde",
    "6821": "swde",
    "6823": "swde",
    "6824": "swde",
    "6840": "swde",
    "6850": "swde",
    "6851": "swde",
    "6852": "swde",
    "6853": "swde",
    "6856": "swde",
    "6880": "swde",
    "6887": "swde",
    "6900": "swde",
    "6920": "swde",
    "6921": "swde",
    "6922": "swde",
    "6924": "swde",
    "6929": "swde",
    "6940": "swde",
    "6941": "swde",
    "6980": "swde",
    "6982": "swde",
    "6983": "swde",
    "6984": "swde",
    "6986": "swde",
    "6987": "swde",
    "6990": "aiec",
    "7000": "swde",
    "7010": "swde",
    "7012": "swde",
    "7020": "swde",
    "7021": "swde",
    "7022": "swde",
    "7024": "swde",
    "7030": "swde",
    "7031": "swde",
    "7032": "swde",
    "7033": "swde",
    "7034": "swde",
    "7040": "swde",
    "7041": "swde",
    "7050": "swde",
    "7060": "swde",
    "7061": "swde",
    "7062": "swde",
    "7063": "swde",
    "7070": "swde",
    "7080": "swde",
    "7090": "swde",
    "7100": "swde",
    "7110": "swde",
    "7120": "swde",
    "7130": "swde",
    "7131": "swde",
    "7133": "swde",
    "7134": "swde",
    "7140": "swde",
    "7141": "swde",
    "7160": "swde",
    "7170": "swde",
    "7180": "swde",
    "7181": "swde",
    "7190": "swde",
    "7191": "swde",
    "7300": "swde",
    "7301": "swde",
    "7320": "swde",
    "7321": "swde",
    "7322": "swde",
    "7330": "swde",
    "7331": "swde",
    "7332": "swde",
    "7333": "swde",
    "7334": "swde",
    "7340": "swde",
    "7350": "swde",
    "7370": "swde",
    "7380": "swde",
    "7382": "swde",
    "7387": "swde",
    "7390": "swde",
    "7500": "swde",
    "7501": "swde",
    "7502": "swde",
    "7503": "swde",
    "7504": "swde",
    "7506": "swde",
    "7510": "swde",
    "7511": "swde",
    "7512": "swde",
    "7513": "swde",
    "7520": "swde",
    "7521": "swde",
    "7522": "swde",
    "7530": "swde",
    "7531": "swde",
    "7532": "swde",
    "7533": "swde",
    "7534": "swde",
    "7536": "swde",
    "7538": "swde",
    "7540": "swde",
    "7542": "swde",
    "7543": "swde",
    "7548": "swde",
    "7600": "swde",
    "7601": "swde",
    "7602": "swde",
    "7603": "swde",
    "7604": "swde",
    "7608": "swde",
    "7610": "swde",
    "7611": "swde",
    "7618": "swde",
    "7620": "swde",
    "7621": "swde",
    "7622": "swde",
    "7623": "swde",
    "7624": "swde",
    "7640": "swde",
    "7641": "swde",
    "7642": "swde",
    "7643": "swde",
    "7700": "ieg",
    "7711": "swde",
    "7712": "ieg",
    "7730": "swde",
    "7740": "swde",
    "7742": "swde",
    "7743": "swde",
    "7750": "swde",
    "7760": "swde",
    "7780": "swde",
    "7781": "swde",
    "7782": "swde",
    "7783": "swde",
    "7784": "swde",
    "7800": "swde",
    "7801": "swde",
    "7802": "swde",
    "7803": "swde",
    "7804": "swde",
    "7810": "swde",
    "7811": "swde",
    "7812": "swde",
    "7822": "swde",
    "7823": "swde",
    "7830": "swde",
    "7850": "swde",
    "7860": "swde",
    "7861": "swde",
    "7862": "swde",
    "7863": "swde",
    "7864": "swde",
    "7866": "swde",
    "7870": "swde",
    "7880": "swde",
    "7890": "swde",
    "7900": "swde",
    "7901": "swde",
    "7903": "swde",
    "7904": "swde",
    "7906": "swde",
    "7910": "swde",
    "7911": "swde",
    "7912": "swde",
    "7940": "swde",
    "7941": "swde",
    "7942": "swde",
    "7943": "swde",
    "7950": "swde",
    "7951": "swde",
    "7970": "swde",
    "7971": "swde",
    "7972": "swde",
    "7973": "swde",
}


# Postcodes genuinely split between two or three operators at street
# level: the user can't be assigned automatically because the answer
# depends on which street/parish of the postcode they live on. The
# config flow shows a small chooser populated with this tuple; the
# first entry is what the legacy range-based resolver would have
# picked (so the behaviour is backwards-compatible if a caller
# accidentally goes through ``resolve`` instead of
# ``resolve_candidates``).
_SPLIT_POSTCODES: dict[str, tuple[str, ...]] = {
    "1770": ("de_watergroep", "farys"),  # Liedekerke
    "8020": ("farys", "de_watergroep"),  # Oostkamp
    "8400": ("farys", "de_watergroep"),  # Oostende (Stene/Mariakerke)
    "8450": ("aquaduin", "de_watergroep"),  # Bredene
    "8490": ("farys", "de_watergroep"),  # Jabbeke
    "9080": ("farys", "de_watergroep"),  # Lochristi
    "9550": ("farys", "de_watergroep"),  # Herzele
    "9570": ("farys", "de_watergroep"),  # Lierde
}


def resolve_candidates(postcode: str | None) -> tuple[str, ...]:
    """Return every utility plausibly serving ``postcode``.

    Returns:
        Empty tuple if the postcode is unknown / unresolvable.
        Single-element tuple for unambiguous postcodes.
        Multi-element tuple for postcodes genuinely split between
        operators at street level (see ``_SPLIT_POSTCODES``).
    """
    if not postcode:
        return ()
    try:
        code = int(postcode)
    except (TypeError, ValueError):
        return ()
    key = str(code).zfill(4)
    if key in _SPLIT_POSTCODES:
        return _SPLIT_POSTCODES[key]
    single = _resolve_single(code)
    return (single,) if single else ()


def _resolve_single(code: int) -> str | None:
    """Range / table-based resolution for non-split postcodes."""
    # Brussels.
    if 1000 <= code <= 1299:
        return "vivaqua"
    # Brabant Wallon.
    if 1300 <= code <= 1499:
        return "inbw"
    # Antwerp city core is Water-link; rest of the province is Pidpa. Ring
    # communes (Edegem, Hove, Mortsel, etc.) overlap with Pidpa's wider
    # service area so we default to Pidpa there and let the user override
    # via the manual picker.
    if 2000 <= code <= 2070:
        return "water_link"
    if 2000 <= code <= 2999:
        return "pidpa"
    # Vlaams-Brabant + Halle-Vilvoorde + Limburg.
    if 1500 <= code <= 1999 or 3000 <= code <= 3999:
        return "de_watergroep"
    # Wallonia: trust the ZDE-derived per-postcode table first. If the
    # postcode isn't in it the user is most likely on a régies communales
    # we don't ship -- return None so they hit the manual picker rather
    # than mis-defaulting to SWDE.
    if 4000 <= code <= 7999:
        return _PER_POSTCODE.get(str(code).zfill(4))
    # Flanders carve-outs in West-Vl.
    if code in (8300, 8301):
        return "agso_knokke"
    if code in _AQUADUIN_POSTCODES:
        return "aquaduin"
    # DWG-served pockets scattered inside the otherwise-Farys block
    # (Kortrijk, Harelbeke, Roeselare, Waregem, Ieper, Sint-Niklaas's
    # outer parishes, Eeklo, Maldegem, etc.). AGSO + Aquaduin carve-outs
    # above win first for the few postcodes they overlap.
    if code in _DWG_POSTCODES_FLANDERS:
        return "de_watergroep"
    # Most of West-Vl. + Oost-Vl. is Farys territory; the carve-outs above
    # (AGSO, Aquaduin, DWG) win first.
    if 8000 <= code <= 9999:
        return "farys"
    return None


def resolve(postcode: str | None) -> str | None:
    """Return the dominant utility for ``postcode``, or ``None`` if unknown.

    Convenience wrapper around :func:`resolve_candidates`. For postcodes
    in :data:`_SPLIT_POSTCODES` this returns the first candidate (the
    operator the legacy range rule would have picked); callers that
    need to surface a chooser should use :func:`resolve_candidates`
    directly.
    """
    candidates = resolve_candidates(postcode)
    return candidates[0] if candidates else None
