"""Postcode → utility resolver.

v0.1 hard-codes Brussels-Capital region (1000-1299 → VIVAQUA). Flanders
and Wallonia ranges land in v0.2 and v0.3, generated by
``scripts/refresh_postcodes.py`` from the VMM Waterloket scrape and the
Géoportail Wallonie ZDE GeoPackage respectively.
"""

from __future__ import annotations


def resolve(postcode: str) -> str | None:
    """Return the utility id serving ``postcode``, or ``None`` if unknown."""
    try:
        code = int(postcode)
    except ValueError:
        return None
    if 1000 <= code <= 1299:
        return "vivaqua"
    return None
